name: Deploy Docs to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch: {}

# Allow GITHUB_TOKEN to deploy to gh-pages
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          # fetch-depth 0 lets peaceiris action keep commit history if desired
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build static site
        run: npm run build

      # Deploy to gh-pages branch
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./build
          force_orphan: true
          # Optionally retain history: set force_orphan to false if you prefer history
